export const LOAD_PANNEAUX = "LOAD_PANNEAUX";
export const LOAD_BOISBLANC = "LOAD_BOISBLANC";
export const LOAD_BOISDUR = "LOAD_BOISDUR";
export const LOAD_BOISROUGE = "LOAD_BOISROUGE";
export const LOAD_CONTREPAQUE = "LOAD_CONTREPLAQUE";
export const LOAD_ALLCLIENTS = "LOAD_ALLCLIENTS";
export const LOAD_FACTURES = "LOAD_FACTURES";
